### ISSUE TITLE
map size smaller than 10km doesn't work

### ISSUE THREAD

**Issue by joceyngan** [sysoppl/Cities-Skylines-heightmap-generator#87]
I am getting this issue on https://heightmap.skydark.pl/ and found this repo is the related code so raise it here.
if i decrease the map size to smaller than 10km, the calculation on base level and height level will stuck and never output the min max height.
is there a fix if just want to create the height map from a very small area? thanks

**Comment by echoflying** [comment]
I set to 9km, the satellite map download correct, but the height map download failue, no response at all.
with error information:
app.js:1068 Uncaught TypeError: Cannot read properties of undefined (reading '1623')
    at toHeightmap (app.js:1068:76)
    at app.js:645:29

Set to 10km, the height map can download but the content is all black.
